import type {
  Allergy,
  AppData,
  DietaryRestriction,
  Family,
  FamilyMember,
  FoodPreference,
  FreezerInventory,
  Ingredient,
  MenuPlan,
  MenuPlanItem,
  PantryInventory,
  Profile,
  Recipe,
  RecipeIngredient,
  ShoppingList,
  ShoppingListItem,
} from './types'
import { addDays, normalizeName, todayIso } from './utils'

const now = new Date().toISOString()
const today = todayIso()

export const ids = {
  chef: '00000000-0000-4000-8000-000000000001',
  family: '10000000-0000-4000-8000-000000000001',
  soren: '20000000-0000-4000-8000-000000000001',
  flor: '20000000-0000-4000-8000-000000000002',
  galeano: '20000000-0000-4000-8000-000000000003',
  plan: '30000000-0000-4000-8000-000000000001',
  shopping: '40000000-0000-4000-8000-000000000001',
}

const profile: Profile = {
  id: ids.chef,
  full_name: 'Flor & Galeano Chef',
  email: 'chef@smartfamilymeals.local',
  role: 'chef',
  preferred_language: 'en',
  avatar_url: '',
  created_at: now,
  updated_at: now,
}

const family: Family = {
  id: ids.family,
  name: 'Galeano Family',
  description: 'Active family nutrition program with allergy-aware menu planning.',
  primary_contact_name: 'Flor Galeano',
  primary_contact_email: 'flor@example.com',
  primary_contact_phone: '+1 555 0100',
  address: 'Family residence',
  notes: 'Prefers chef-ready weekly plans with freezer backup meals.',
  owner_id: ids.chef,
  chef_id: ids.chef,
  created_at: now,
  updated_at: now,
}

const familyMembers: FamilyMember[] = [
  {
    id: ids.soren,
    family_id: ids.family,
    full_name: 'Soren Galeano',
    nickname: 'Soren',
    age_years: 9,
    activity_level: 'high',
    portion_factor: 1.3,
    daily_calorie_target: 2200,
    daily_protein_target_g: 70,
    notes: 'Avoids visible melted cheese. Allows grated parmesan.',
    is_active: true,
    created_at: now,
    updated_at: now,
  },
  {
    id: ids.flor,
    family_id: ids.family,
    full_name: 'Flor Galeano',
    nickname: 'Flor',
    age_years: 38,
    activity_level: 'moderate',
    portion_factor: 1,
    daily_calorie_target: 1900,
    daily_protein_target_g: 72,
    notes: 'Prefers varied proteins and vegetable-forward meals.',
    is_active: true,
    created_at: now,
    updated_at: now,
  },
  {
    id: ids.galeano,
    family_id: ids.family,
    full_name: 'Galeano',
    nickname: 'Galeano',
    age_years: 41,
    activity_level: 'moderate',
    portion_factor: 1.1,
    daily_calorie_target: 2300,
    daily_protein_target_g: 90,
    notes: 'Prefers hearty lunch and dinner portions.',
    is_active: true,
    created_at: now,
    updated_at: now,
  },
]

const allergies: Allergy[] = [
  ['gluten', 'severe', true],
  ['wheat', 'severe', true],
  ['rye', 'severe', true],
  ['barley', 'severe', true],
  ['tree nuts', 'severe', true],
  ['sesame', 'anaphylaxis', true],
  ['tahini', 'anaphylaxis', true],
  ['sunflower seeds', 'severe', true],
  ['sunflower butter', 'severe', true],
  ['sunflower flour', 'severe', true],
  ['lentils', 'moderate', false],
].map(([name, severity, avoid], index) => ({
  id: `allergy-${index + 1}`,
  family_member_id: ids.soren,
  allergen_name: String(name),
  normalized_allergen_name: normalizeName(String(name)),
  severity: severity as Allergy['severity'],
  reaction_notes:
    name === 'lentils' ? 'Generic lentils require review; red, green, brown and black lentils are allowed.' : undefined,
  avoid_traces: Boolean(avoid),
  cross_contact_risk: true,
  emergency_notes: name === 'sesame' ? 'Avoid sesame and tahini in all forms.' : undefined,
  created_at: now,
  updated_at: now,
}))

const dietaryRestrictions: DietaryRestriction[] = [
  {
    id: 'restriction-1',
    family_member_id: ids.soren,
    restriction_type: 'cheese_visibility',
    description: 'No visible melted cheese; grated parmesan is acceptable.',
    is_medical: false,
    created_at: now,
  },
]

const foodPreferences: FoodPreference[] = [
  ['dislikes', 'visible melted cheese', 'Allows grated parmesan.'],
  ['likes', 'beef', 'Preferred protein.'],
  ['likes', 'smoked salmon', 'Preferred protein.'],
  ['likes', 'lobster', 'Preferred seafood.'],
  ['likes', 'oysters', 'Preferred seafood.'],
  ['likes', 'chicken', 'Preferred protein.'],
  ['likes', 'ground turkey', 'Preferred protein.'],
  ['favorite', 'pizza without cheese, tomato sauce and pepperoni', 'Must be gluten-free.'],
  ['likes', 'colorful fruits', 'Rotate colors during the week.'],
].map(([preference_type, item_name, notes], index) => ({
  id: `pref-${index + 1}`,
  family_member_id: ids.soren,
  preference_type: preference_type as FoodPreference['preference_type'],
  item_name: String(item_name),
  notes: String(notes),
  created_at: now,
}))

function ingredient(
  id: string,
  name: string,
  category: string,
  nutrition: Partial<Ingredient>,
  allergy: Partial<Ingredient> = {},
): Ingredient {
  return {
    id,
    owner_id: ids.chef,
    family_id: ids.family,
    scope: 'family',
    name,
    normalized_name: normalizeName(name),
    category,
    default_unit: 'g',
    calories_per_100g: nutrition.calories_per_100g ?? 0,
    protein_g_per_100g: nutrition.protein_g_per_100g ?? 0,
    carbs_g_per_100g: nutrition.carbs_g_per_100g ?? 0,
    fat_g_per_100g: nutrition.fat_g_per_100g ?? 0,
    fiber_g_per_100g: nutrition.fiber_g_per_100g ?? 0,
    sugar_g_per_100g: nutrition.sugar_g_per_100g ?? 0,
    sodium_mg_per_100g: nutrition.sodium_mg_per_100g ?? 0,
    calcium_mg_per_100g: nutrition.calcium_mg_per_100g ?? 0,
    iron_mg_per_100g: nutrition.iron_mg_per_100g ?? 0,
    contains_gluten: allergy.contains_gluten ?? false,
    contains_dairy: allergy.contains_dairy ?? false,
    contains_egg: allergy.contains_egg ?? false,
    contains_fish: allergy.contains_fish ?? false,
    contains_shellfish: allergy.contains_shellfish ?? false,
    contains_tree_nuts: allergy.contains_tree_nuts ?? false,
    contains_peanuts: allergy.contains_peanuts ?? false,
    contains_sesame: allergy.contains_sesame ?? false,
    contains_soy: allergy.contains_soy ?? false,
    allergen_tags: allergy.allergen_tags ?? [],
    may_contain_tags: allergy.may_contain_tags ?? [],
    allowed_exceptions: allergy.allowed_exceptions ?? [],
    blocked_derivatives: allergy.blocked_derivatives ?? [],
    source: 'manual',
    external_source_id: '',
    cost_per_unit: nutrition.cost_per_unit ?? 0,
    package_size: nutrition.package_size ?? 0,
    package_unit: nutrition.package_unit ?? 'g',
    notes: allergy.notes,
    created_at: now,
    updated_at: now,
  }
}

export const ingredients: Ingredient[] = [
  ingredient('ing-beef', 'Beef', 'protein', { calories_per_100g: 250, protein_g_per_100g: 26, fat_g_per_100g: 15, iron_mg_per_100g: 2.6, cost_per_unit: 0.018 }),
  ingredient('ing-ground-turkey', 'Ground turkey', 'protein', { calories_per_100g: 189, protein_g_per_100g: 27, fat_g_per_100g: 8, sodium_mg_per_100g: 75, cost_per_unit: 0.014 }),
  ingredient('ing-chicken', 'Chicken', 'protein', { calories_per_100g: 165, protein_g_per_100g: 31, fat_g_per_100g: 3.6, sodium_mg_per_100g: 74, cost_per_unit: 0.012 }),
  ingredient('ing-smoked-salmon', 'Smoked salmon', 'protein', { calories_per_100g: 117, protein_g_per_100g: 18, fat_g_per_100g: 4.3, sodium_mg_per_100g: 672, cost_per_unit: 0.032 }, { contains_fish: true, allergen_tags: ['fish'] }),
  ingredient('ing-rice', 'Rice', 'grain', { calories_per_100g: 130, protein_g_per_100g: 2.7, carbs_g_per_100g: 28, fat_g_per_100g: 0.3 }),
  ingredient('ing-sweet-potato', 'Sweet potato', 'vegetable', { calories_per_100g: 86, protein_g_per_100g: 1.6, carbs_g_per_100g: 20, fiber_g_per_100g: 3, sugar_g_per_100g: 4.2 }),
  ingredient('ing-tomato', 'Tomato', 'vegetable', { calories_per_100g: 18, protein_g_per_100g: 0.9, carbs_g_per_100g: 3.9, fiber_g_per_100g: 1.2, sugar_g_per_100g: 2.6 }),
  ingredient('ing-tomato-sauce', 'Tomato sauce', 'sauce', { calories_per_100g: 29, protein_g_per_100g: 1.3, carbs_g_per_100g: 6, fiber_g_per_100g: 1.5, sodium_mg_per_100g: 400 }),
  ingredient('ing-pepperoni', 'Pepperoni', 'protein', { calories_per_100g: 494, protein_g_per_100g: 23, fat_g_per_100g: 44, sodium_mg_per_100g: 1761 }),
  ingredient('ing-gf-flour', 'Gluten-free flour', 'baking', { calories_per_100g: 360, protein_g_per_100g: 5, carbs_g_per_100g: 78, fiber_g_per_100g: 3 }, { allergen_tags: [] }),
  ingredient('ing-almonds', 'Almonds', 'nuts', { calories_per_100g: 579, protein_g_per_100g: 21, carbs_g_per_100g: 22, fat_g_per_100g: 50, fiber_g_per_100g: 12.5, calcium_mg_per_100g: 269, iron_mg_per_100g: 3.7 }, { contains_tree_nuts: true, allergen_tags: ['tree nuts'], allowed_exceptions: ['almond', 'almonds'] }),
  ingredient('ing-olive-oil', 'Olive oil', 'oil', { calories_per_100g: 884, fat_g_per_100g: 100 }),
  ingredient('ing-sunflower-oil', 'Sunflower oil', 'oil', { calories_per_100g: 884, fat_g_per_100g: 100 }, { allowed_exceptions: ['sunflower oil'] }),
  ingredient('ing-sunflower-lecithin', 'Sunflower lecithin', 'additive', { calories_per_100g: 763, fat_g_per_100g: 100 }, { allowed_exceptions: ['sunflower lecithin'] }),
  ingredient('ing-sesame', 'Sesame', 'seed', { calories_per_100g: 573, protein_g_per_100g: 18, carbs_g_per_100g: 23, fat_g_per_100g: 50 }, { contains_sesame: true, allergen_tags: ['sesame'] }),
  ingredient('ing-tahini', 'Tahini', 'spread', { calories_per_100g: 595, protein_g_per_100g: 17, carbs_g_per_100g: 21, fat_g_per_100g: 54 }, { contains_sesame: true, allergen_tags: ['sesame', 'tahini'] }),
  ingredient('ing-wheat', 'Wheat', 'grain', { calories_per_100g: 340, protein_g_per_100g: 13, carbs_g_per_100g: 72, fiber_g_per_100g: 10 }, { contains_gluten: true, allergen_tags: ['gluten', 'wheat'] }),
  ingredient('ing-barley', 'Barley', 'grain', { calories_per_100g: 354, protein_g_per_100g: 12, carbs_g_per_100g: 73, fiber_g_per_100g: 17 }, { contains_gluten: true, allergen_tags: ['gluten', 'barley'] }),
  ingredient('ing-rye', 'Rye', 'grain', { calories_per_100g: 338, protein_g_per_100g: 10, carbs_g_per_100g: 76, fiber_g_per_100g: 15 }, { contains_gluten: true, allergen_tags: ['gluten', 'rye'] }),
  ingredient('ing-red-lentils', 'Red lentils', 'legume', { calories_per_100g: 116, protein_g_per_100g: 9, carbs_g_per_100g: 20, fiber_g_per_100g: 8 }),
  ingredient('ing-generic-lentils', 'Generic lentils', 'legume', { calories_per_100g: 116, protein_g_per_100g: 9, carbs_g_per_100g: 20, fiber_g_per_100g: 8 }, { allergen_tags: ['lentils'] }),
  ingredient('ing-banana', 'Banana', 'fruit', { calories_per_100g: 89, protein_g_per_100g: 1.1, carbs_g_per_100g: 23, fiber_g_per_100g: 2.6, sugar_g_per_100g: 12 }),
  ingredient('ing-apple', 'Apple', 'fruit', { calories_per_100g: 52, protein_g_per_100g: 0.3, carbs_g_per_100g: 14, fiber_g_per_100g: 2.4, sugar_g_per_100g: 10 }),
  ingredient('ing-strawberry', 'Strawberry', 'fruit', { calories_per_100g: 32, protein_g_per_100g: 0.7, carbs_g_per_100g: 7.7, fiber_g_per_100g: 2, sugar_g_per_100g: 4.9 }),
  ingredient('ing-blueberry', 'Blueberry', 'fruit', { calories_per_100g: 57, protein_g_per_100g: 0.7, carbs_g_per_100g: 14, fiber_g_per_100g: 2.4, sugar_g_per_100g: 10 }),
  ingredient('ing-mango', 'Mango', 'fruit', { calories_per_100g: 60, protein_g_per_100g: 0.8, carbs_g_per_100g: 15, fiber_g_per_100g: 1.6, sugar_g_per_100g: 14 }),
  ingredient('ing-cucumber', 'Cucumber', 'vegetable', { calories_per_100g: 15, protein_g_per_100g: 0.7, carbs_g_per_100g: 3.6, fiber_g_per_100g: 0.5, sugar_g_per_100g: 1.7 }),
  ingredient('ing-sunflower-seeds', 'Sunflower seeds', 'seed', { calories_per_100g: 584, protein_g_per_100g: 21, carbs_g_per_100g: 20, fat_g_per_100g: 51 }, { allergen_tags: ['sunflower seeds'] }),
]

function recipe(
  id: string,
  name: string,
  category: string,
  mainProtein: string,
  mealStyle: string,
  flags: Partial<Recipe> = {},
): Recipe {
  return {
    id,
    owner_id: ids.chef,
    family_id: ids.family,
    scope: 'family',
    name,
    description: `${name} prepared for family service.`,
    category,
    cuisine_type: 'family',
    main_protein: mainProtein,
    meal_style: mealStyle,
    prep_time_minutes: 20,
    cook_time_minutes: 25,
    servings: flags.servings ?? 4,
    serving_size_g: flags.serving_size_g ?? 280,
    instructions: flags.instructions ?? 'Prep ingredients. Cook safely. Portion by diner factors. Label allergens before service.',
    reheating_instructions: flags.reheating_instructions ?? 'Reheat gently until hot throughout.',
    chef_notes: flags.chef_notes ?? '',
    is_freezer_friendly: flags.is_freezer_friendly ?? false,
    is_school_friendly: flags.is_school_friendly ?? false,
    is_gluten_free: flags.is_gluten_free ?? true,
    visible_melted_cheese: flags.visible_melted_cheese ?? false,
    status: flags.status ?? 'active',
    image_url: flags.image_url,
    ai_generated: flags.ai_generated ?? false,
    created_at: now,
    updated_at: now,
  }
}

export const recipes: Recipe[] = [
  recipe('rec-gf-pizza', 'Gluten-Free Cheese-Free Pepperoni Pizza', 'dinner', 'pepperoni', 'comfort', { is_school_friendly: true }),
  recipe('rec-beef-rice-bowl', 'Beef Rice Bowl with Vegetables', 'lunch', 'beef', 'bowl', { is_freezer_friendly: true }),
  recipe('rec-turkey-meatballs', 'Ground Turkey Meatballs with Tomato Sauce', 'dinner', 'ground turkey', 'batch', { is_freezer_friendly: true }),
  recipe('rec-roasted-chicken', 'Roasted Chicken with Sweet Potatoes', 'dinner', 'chicken', 'sheet-pan', { is_freezer_friendly: true }),
  recipe('rec-salmon-rice', 'Smoked Salmon Rice Bowl with Cucumber', 'lunch', 'smoked salmon', 'bowl', { is_school_friendly: true }),
  recipe('rec-banana-muffins', 'Gluten-Free Banana Muffins', 'snack', 'none', 'baked snack', { is_school_friendly: true, serving_size_g: 90 }),
  recipe('rec-fruit-skewers', 'Rainbow Fruit Skewers', 'snack', 'none', 'fresh snack', { is_school_friendly: true, prep_time_minutes: 12, cook_time_minutes: 0, serving_size_g: 180 }),
  recipe('rec-gf-bread', 'Gluten-Free Lunchbox Bread', 'school_lunch', 'none', 'bread', { is_school_friendly: true, is_freezer_friendly: true, serving_size_g: 80 }),
  recipe('rec-beef-burger', 'Beef Burger with Gluten-Free Bun', 'dinner', 'beef', 'grill', { is_school_friendly: false }),
  recipe('rec-gf-tacos', 'Gluten-Free Tortilla Tacos', 'dinner', 'beef', 'tacos', { is_school_friendly: true }),
  recipe('rec-wheat-pasta', 'Regular Wheat Pasta with Sauce', 'dinner', 'none', 'pasta', { is_gluten_free: false }),
  recipe('rec-hummus-tahini', 'Hummus with Tahini', 'snack', 'chickpea', 'dip', { is_gluten_free: true }),
  recipe('rec-wheat-sandwich', 'Wheat Bread Sandwich', 'school_lunch', 'turkey', 'sandwich', { is_gluten_free: false }),
  recipe('rec-sesame-salad', 'Sesame Seed Salad', 'lunch', 'none', 'salad', { is_gluten_free: true }),
  recipe('rec-lentil-soup', 'Generic Lentil Soup', 'lunch', 'lentils', 'soup', { is_gluten_free: true, status: 'draft' }),
]

const ri = (recipe_id: string, ingredient_id: string, quantity_g: number, note = ''): RecipeIngredient => ({
  id: `ri-${recipe_id}-${ingredient_id}`,
  recipe_id,
  ingredient_id,
  quantity_g,
  display_quantity: `${quantity_g} g`,
  is_optional: false,
  preparation_note: note,
  notes: '',
  created_at: now,
})

export const recipeIngredients: RecipeIngredient[] = [
  ri('rec-gf-pizza', 'ing-gf-flour', 360),
  ri('rec-gf-pizza', 'ing-tomato-sauce', 240),
  ri('rec-gf-pizza', 'ing-pepperoni', 140),
  ri('rec-gf-pizza', 'ing-olive-oil', 28),
  ri('rec-beef-rice-bowl', 'ing-beef', 520),
  ri('rec-beef-rice-bowl', 'ing-rice', 360),
  ri('rec-beef-rice-bowl', 'ing-tomato', 260),
  ri('rec-turkey-meatballs', 'ing-ground-turkey', 800),
  ri('rec-turkey-meatballs', 'ing-rice', 400),
  ri('rec-turkey-meatballs', 'ing-tomato-sauce', 300),
  ri('rec-turkey-meatballs', 'ing-olive-oil', 40),
  ri('rec-roasted-chicken', 'ing-chicken', 720),
  ri('rec-roasted-chicken', 'ing-sweet-potato', 520),
  ri('rec-roasted-chicken', 'ing-olive-oil', 32),
  ri('rec-salmon-rice', 'ing-smoked-salmon', 360),
  ri('rec-salmon-rice', 'ing-rice', 420),
  ri('rec-salmon-rice', 'ing-cucumber', 240),
  ri('rec-banana-muffins', 'ing-banana', 320),
  ri('rec-banana-muffins', 'ing-gf-flour', 260),
  ri('rec-banana-muffins', 'ing-olive-oil', 36),
  ri('rec-fruit-skewers', 'ing-strawberry', 220),
  ri('rec-fruit-skewers', 'ing-blueberry', 160),
  ri('rec-fruit-skewers', 'ing-mango', 220),
  ri('rec-fruit-skewers', 'ing-apple', 180),
  ri('rec-gf-bread', 'ing-gf-flour', 500),
  ri('rec-gf-bread', 'ing-olive-oil', 40),
  ri('rec-beef-burger', 'ing-beef', 600),
  ri('rec-beef-burger', 'ing-gf-flour', 260),
  ri('rec-gf-tacos', 'ing-beef', 420),
  ri('rec-gf-tacos', 'ing-tomato', 180),
  ri('rec-wheat-pasta', 'ing-wheat', 400),
  ri('rec-wheat-pasta', 'ing-tomato-sauce', 260),
  ri('rec-hummus-tahini', 'ing-tahini', 90),
  ri('rec-hummus-tahini', 'ing-olive-oil', 24),
  ri('rec-wheat-sandwich', 'ing-wheat', 240),
  ri('rec-sesame-salad', 'ing-sesame', 35),
  ri('rec-sesame-salad', 'ing-cucumber', 220),
  ri('rec-lentil-soup', 'ing-generic-lentils', 300),
  ri('rec-lentil-soup', 'ing-tomato', 160),
]

const menuPlans: MenuPlan[] = [
  {
    id: ids.plan,
    family_id: ids.family,
    name: 'Galeano Family Weekly Plan',
    start_date: today,
    end_date: addDays(today, 6),
    status: 'planned',
    created_by: ids.chef,
    created_at: now,
    updated_at: now,
  },
]

const menuPlanItems: MenuPlanItem[] = [
  {
    id: 'mpi-1',
    menu_plan_id: ids.plan,
    recipe_id: 'rec-turkey-meatballs',
    planned_date: today,
    meal_time: 'dinner',
    servings: 1,
    portion_factor: 1,
    planned_grams: 320,
    calories: 520,
    protein_g: 38,
    allergy_status: 'safe',
    variety_status: 'allowed',
    created_at: now,
    updated_at: now,
  },
  {
    id: 'mpi-2',
    menu_plan_id: ids.plan,
    recipe_id: 'rec-salmon-rice',
    planned_date: addDays(today, 1),
    meal_time: 'lunch',
    servings: 1,
    portion_factor: 1,
    planned_grams: 280,
    calories: 420,
    protein_g: 28,
    allergy_status: 'safe',
    variety_status: 'allowed',
    created_at: now,
    updated_at: now,
  },
  {
    id: 'mpi-history',
    menu_plan_id: ids.plan,
    recipe_id: 'rec-gf-pizza',
    planned_date: addDays(today, -10),
    meal_time: 'dinner',
    servings: 1,
    portion_factor: 1,
    planned_grams: 300,
    calories: 600,
    protein_g: 22,
    allergy_status: 'safe',
    variety_status: 'allowed',
    created_at: now,
    updated_at: now,
  },
]

const pantryInventory: PantryInventory[] = [
  ['ing-ground-turkey', 300, 600, addDays(today, 4), 'fridge'],
  ['ing-rice', 1000, 500, addDays(today, 160), 'pantry'],
  ['ing-tomato-sauce', 120, 300, addDays(today, 45), 'pantry'],
  ['ing-olive-oil', 600, 200, addDays(today, 300), 'pantry'],
  ['ing-smoked-salmon', 200, 250, addDays(today, 3), 'fridge'],
  ['ing-cucumber', 80, 150, addDays(today, 5), 'fridge'],
  ['ing-gf-flour', 700, 500, addDays(today, 120), 'pantry'],
].map(([ingredient_id, quantity_available, min_quantity_alert, expiration_date, location], index) => ({
  id: `pantry-${index + 1}`,
  family_id: ids.family,
  ingredient_id: String(ingredient_id),
  quantity_available: Number(quantity_available),
  unit: 'g',
  min_quantity_alert: Number(min_quantity_alert),
  expiration_date: String(expiration_date),
  location: String(location),
  notes: '',
  created_at: now,
  updated_at: now,
}))

const freezerInventory: FreezerInventory[] = [
  {
    id: 'freezer-1',
    family_id: ids.family,
    recipe_id: 'rec-beef-rice-bowl',
    prepared_date: addDays(today, -8),
    expiration_date: addDays(today, 6),
    portions_available: 3,
    grams_per_portion: 310,
    reheating_instructions: 'Reheat covered with a splash of water.',
    storage_notes: 'Label as gluten-free.',
    created_at: now,
    updated_at: now,
  },
  {
    id: 'freezer-2',
    family_id: ids.family,
    recipe_id: 'rec-roasted-chicken',
    prepared_date: addDays(today, -5),
    expiration_date: addDays(today, 18),
    portions_available: 6,
    grams_per_portion: 330,
    reheating_instructions: 'Oven or microwave until hot.',
    storage_notes: 'Pair with fresh fruit for lunch.',
    created_at: now,
    updated_at: now,
  },
]

const shoppingLists: ShoppingList[] = [
  {
    id: ids.shopping,
    family_id: ids.family,
    menu_plan_id: ids.plan,
    name: 'Weekly Kitchen Purchase',
    status: 'active',
    created_at: now,
    updated_at: now,
  },
]

const shoppingListItems: ShoppingListItem[] = [
  {
    id: 'shop-1',
    shopping_list_id: ids.shopping,
    ingredient_id: 'ing-ground-turkey',
    required_quantity: 800,
    available_quantity: 300,
    missing_quantity: 500,
    unit: 'g',
    is_checked: false,
    notes: '',
    created_at: now,
  },
  {
    id: 'shop-2',
    shopping_list_id: ids.shopping,
    ingredient_id: 'ing-tomato-sauce',
    required_quantity: 300,
    available_quantity: 120,
    missing_quantity: 180,
    unit: 'g',
    is_checked: false,
    notes: '',
    created_at: now,
  },
]

export const demoData: AppData = {
  profiles: [profile],
  families: [family],
  familyMembers,
  allergies,
  dietaryRestrictions,
  foodPreferences,
  ingredients,
  recipes,
  recipeIngredients,
  menuPlans,
  menuPlanItems,
  pantryInventory,
  freezerInventory,
  shoppingLists,
  shoppingListItems,
  alerts: [],
  settings: {
    id: 'settings-1',
    owner_id: ids.chef,
    gemini_enabled: false,
    ai_model: 'gemini-2.5-flash',
    default_variety_days: 21,
    default_units: 'metric',
    default_language: 'en',
    theme: 'light',
    nutrition_low_threshold_pct: 0.85,
    allergy_strictness: 'strict',
    created_at: now,
    updated_at: now,
  },
}
